### ISSUE TITLE
Please help, stuck on first_page.xml, swipe or animation not working

### ISSUE THREAD

**Issue by mavinomichael** [Cuberto/liquid-swipe-android#1]
I cloned the project created a Github.properties file ran a build and first_page.xml launched with no interactions working. no swipe no animation. Some part of the layout is even cut off from the screen.
check out the screenshot. Thanks.
![Screenshot_20200117-130857](https://user-images.githubusercontent.com/34043759/72611541-a94c9700-392a-11ea-931e-397f0051173d.png)

**Comment by ersanin** [comment]
What device do you use and what android version does it run? Also if you're cloning the project you don't need Github.properties file - just remove Gradle code that needs it.

**Comment by mavinomichael** [comment]
Thanks it finally worked. I commented out that part in the Gradle code that requires the Github.properties file like this
//def githubProperties = new Properties()
//githubProperties.load(new FileInputStream(rootProject.file("github.properties")))

 repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/Cuberto/liquid-swipe-android")
//            credentials {
//                username = githubProperties['gpr.usr'] ?: System.getenv("GPR_USER")
//                password = githubProperties['gpr.key'] ?: System.getenv("GPR_API_KEY")
//            }
        }
    }
}
