### ISSUE TITLE
Where to put the repositories code in build.gradle inside the app module that will be using the library

### ISSUE THREAD

**Issue by rushomrong** [Cuberto/liquid-swipe-android#25]
Please see the attached image. I am a new learner of android development. I was trying to add the repository code inside my build.gradle file but it is not working. Can you please let me know, where to put that code in android studio updated version - Dolphin | 2021.3.1 Patch 1

Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
Windows 10 10.0

![Issue1](https://user-images.githubusercontent.com/83186509/199177607-43555d31-4690-4546-8208-f79572641d76.png)

**Comment by bhutta-54** [comment]
i have same issue if u find then share plz

**Comment by rushomrong** [comment]
>  i have same issue if u find then share plz

@bhutta-54 Yes, I have fixed the issue. Now, it is working fine for me. Check out the screenshot of how I fixed the issue

## build.gradle settings screenshot 
![build](https://user-images.githubusercontent.com/83186509/200630524-21617c4f-3d81-401a-85eb-85c6f64da220.png)


## Settings.Gradle 
Code I used to solve the issue. Checkout the screenshot with your code and change the GitHub UID & Access key with yours

![Solved](https://user-images.githubusercontent.com/83186509/200630463-e06ebb3b-ecd8-428c-95fd-16e6a1f23374.png)
